### ISSUE TITLE
Amazing plugin but I have an issue

### ISSUE THREAD

**Issue by fouad1994** [yuanfux/react-native-hsv-color-picker#1]
Can you help me to add transparency picker I am trying but I got many errors it is your plugin so you can add it easier than me.

**Comment by yuanfux** [comment]
If you can specify what do you mean by a transparent picker, I might have a chance to help you out.

**Comment by fouad1994** [comment]
![Screenshot_20190321-165609_Google](https://user-images.githubusercontent.com/35866405/54757265-ed7fe580-4bfa-11e9-8053-0c41539b9c36.jpg)

I hope you understand what I mean? 
rgba(255,255,255,**0.5**)

**Comment by fouad1994** [comment]
Will you help me bro?

**Comment by yuanfux** [comment]
The component aims to deliver a pure HSV picker. The transparency picker is a very customized feature and should be implemented by users. 

The best help I could possibly give is to take a look at [hue picker component](https://github.com/yuanfux/react-native-hsv-color-picker/blob/master/src/HuePicker.js). They are basically same thing. The only difference between `hue picker component` and `transparency picker` as far as I see from your image is the checkerboard background.

I will close this issue for now. If you have any question, feel free to dm me. Or if you find any bug regarding this component, please open an issue.
