### ISSUE TITLE
satValPickerBorderRadius not working as expected

### ISSUE THREAD

**Issue by LeanFourie** [yuanfux/react-native-hsv-color-picker#12]
Trying to set the border radius of the saturation & value picker does not work as expected on Android. I added the `satValPickerBorderRadius={ 20 }` property to the `<HsvColorPicker />` element but the result is as follows:

![Screenshot 2020-10-23 at 17 08 05](https://user-images.githubusercontent.com/22146555/97020876-64592f00-1552-11eb-80d9-dc4ef099307d.png)

Only the top border radius changes, nothing happens to the bottom border radius.

**Comment by ketanvault** [comment]
I'm also experiencing the same problem. Please fix this ASAP.

**Comment by kumbhar-ketan** [comment]
I got it working. I'll add a pull request for this issue today or tomorrow.

**Comment by charitha95** [comment]
@kumbhar-ketan  how did you solve it? I am still having the issue here.
