### ISSUE TITLE
how can i have the hue slider in bottom of the value picker

### ISSUE THREAD

**Issue by anton-thushara** [yuanfux/react-native-hsv-color-picker#13]
is there any way to have the hue slider in the bottom of the value picker rather than having it in the right side?

**Comment by anton-thushara** [comment]
managed to do it, heres the code
<HsvColorPicker
          huePickerHue={hue}
          onHuePickerDragMove={this.onHuePickerChange}
          onHuePickerPress={this.onHuePickerChange}
          satValPickerHue={hue}
          satValPickerSaturation={sat}
          satValPickerValue={val}
          onSatValPickerDragMove={this.onSatValPickerChange}
          onSatValPickerPress={this.onSatValPickerChange}
          huePickerBorderRadius={5}
          huePickerSliderSize={20}
          containerStyle={{flexDirection: 'column'}}
          huePickerContainerStyle={{transform: [{ rotate: '-90deg'}], marginTop: -90}}
          //satValPickerContainerStyle={{backgroundColor: 'red'}}
          huePickerBarWidth={30}
          //huePickerBarHeight={230}
        />

**Comment by yuanfux** [comment]
glad you figured it out!
