### ISSUE TITLE
onHuePickerDragMove

### ISSUE THREAD

**Issue by Neha1405** [yuanfux/react-native-hsv-color-picker#4]
onHuePickerDragMove method not working

**Comment by yuanfux** [comment]
Thanks for the issue. If you can provide me with more information about error (i.e. code snippets that cause error / screenshots), I might be able to help you out.

**Comment by Neha1405** [comment]
Actully I want only the color slider with tap and drag feature. 
` <HsvColorPicker
          ref={ref => {
            this.pickerColor = ref;
          }}
          huePickerHue={hue}
          onHuePickerDragMove={this.onHuePickerChange}
          onHuePickerPress={this.onHuePickerChange}
          satValPickerHue={hue}
          satValPickerSaturation={sat}
          satValPickerValue={val}
          satValPickerSize={0}
          satValPickerSliderSize={0}
          onSatValPickerDragMove={this.onSatValPickerChange}
          onSatValPickerPress={this.onSatValPickerChange}
          huePickerSliderSize={20}
        />`
![Screenshot_2020-01-17-15-23-39-965_com textcolorpickerdemo](https://user-images.githubusercontent.com/20737394/72602760-cccd0d00-393d-11ea-9052-1cde88af4176.png)

On drag on the slider, the color should be changed and for that, I have used the onHuePickerDragMove method. But it's not dragging and changing the color. Only the onHuePickerPress method is working.

**Comment by yuanfux** [comment]
If you only want the slider, you can do
```js
import HuePicker from 'react-native-hsv-color-picker/src/HuePicker'
```

check out [this file](https://github.com/yuanfux/react-native-hsv-color-picker/blob/master/src/HuePicker.js#L180) for the supported props.

**Comment by Neha1405** [comment]
Thanks for the help. 
But the slider(Dot) is not moving.
`<HuePicker
          hue={hue}
          onDragMove={this.onHuePickerChange}
          onDragStart={this.onHuePickerChange}
          sliderSize={15}
          onPress={this.onHuePickerChange}
        />
//Method
onHuePickerChange({ hue }) {
    this.setState({
      hue,
    });
  }
`

**Comment by yuanfux** [comment]
What I would suggest is to print out the `hue` value in your method or try to change the `hue`  value of the component manually to see if the slider is moving or not. If it is still not working, I'll take a look.

**Comment by Neha1405** [comment]
@yuanfux See here is the video, you will better understand my issue. 
When I try to move the slider (Dot) it's not moving the position, but the color is changing. 
![Screenrecorder-2020-01-17-17-56](https://user-images.githubusercontent.com/20737394/72612756-b16cfc80-3953-11ea-8041-f7510439765e.gif)

**Comment by yuanfux** [comment]
I was on a vocation, sorry for the late replay. 
This is a confirmed bug related to this React Native issue https://github.com/facebook/react-native/issues/27003. This bug should be fixed in the lastest release. I really appreaciate for the issue. If you found more bugs please let me know. Have a good one.
